- internal/provider/mac.go
- internal/provider/resource_network_test.go
- internal/provider/resource_user.go
- internal/provider/resource_wlan.go
- internal/provider/resource_wlan_test.go
I added mac_filtering, since I require it for my home site ...
I imported my current config, that seems to work. 
Also added mac validation in the schema, might make another PR for the user mac address validation there as well.
I'm not quite sure how to write the test for this, I tought adding extra elements in the open wlan test block would solve it, but the test don't seem to go right ...
```
const testAccWLANConfig_open = `
data "unifi_wlan_group" "default" {
}
data "unifi_user_group" "default" {
}
resource "unifi_wlan" "test" {
name          = "tfacc-open"
vlan_id       = 202
wlan_group_id = data.unifi_wlan_group.default.id
user_group_id = data.unifi_user_group.default.id
security      = "open"
mac_filter_enabled = true
mac_filter_list    = ["ab:cd:ef:12:34:56"]
mac_filter_policy  = …
```
> Add mac address filtering

- internal/provider/resource_firewall_rule.go
Firewall rules should be enabled by default. Disabled firewall rules should simply be commented out in Terraform files.
> resource_firewall_rule: enable firewall rules

- .goreleaser.yml
The way the binary is currently built doesn't include the version
number.
This means that `terraform --version` doesn't pick up the version
```shell
$ terraform --version                                                        [130]
Terraform v0.12.24
+ provider.unifi (unversioned)
```
Adding the binary name in line with
https://www.terraform.io/docs/configuration/providers.html#plugin-names-and-versions
will let it show up correctly.
I haven't used goreleaser before, so let me know if there is a nicer method of handling this.
> Added build number to terraform provider binary

- go.mod
- go.sum
- internal/provider/data_radius_profile.go
- internal/provider/lazy_client.go
- internal/provider/provider.go
- internal/provider/resource_wlan.go
- internal/provider/resource_wlan_test.go
Fixes #26, this also requires https://github.com/paultyng/go-unifi/pull/4
> Add support for wpaeap and radius profiles

- .github/dependabot.yml
Saw that that this provider was using GitHub actions. Checking for updates against those actions I thought wouldn't hurt now that dependabot is built into GitHub natively.
> Check for updates to GitHub Actions and Go modules every weekday

- docs/resources/network.md
- internal/provider/resource_network.go
- internal/provider/resource_network_test.go
Adds support to `unifi_network` for IPv6 (only static is tested, not prefix delegation).
Closes #33
> Add IPv6 support to unifi_network

- internal/provider/resource_network.go
wan_type is optional. For example on a purpose = "Corporate" LAN interface this parameter is "". So the default value should be removed.
> wan_type is optional and should not have a default value

- docs/resources/firewall_rule.md
- internal/provider/resource_firewall_rule.go
- internal/provider/resource_firewall_rule_test.go
I noticed this was missing and was using it on a couple of my rules. Let me know if I'm missing anything.
> Added support for destination port on the unifi_firewall_rule resource

- docs/resources/wlan.md
- internal/provider/resource_wlan.go
- internal/provider/resource_wlan_test.go
- internal/provider/resource_wlan_v5_test.go
The no2ghz_oui field maps to this in the Unifi UI:
So I just lifted the description from the UI. hopefully it makes sense.
> Add no2ghz_oui to unifi_wlan resource

- docs/resources/network.md
- examples/resources/unifi_network/import.sh
- internal/provider/lazy_client.go
- internal/provider/provider.go
- internal/provider/resource_network.go
- internal/provider/resource_network_test.go
- internal/provider/resource_wlan_test.go
- E.g. `terraform import unifi_network.mynetwork name=LAN`
- Bumps cidr prefix in tests to avoid:
Call to function "cidrsubnet" failed: prefix extension of 4 does not
accommodate a subnet numbered 18.
> Support importing networks by name

- docs/resources/network.md
- internal/provider/resource_network.go
- internal/provider/resource_network_test.go
Add new fields to `unifi_network` to allow the DNS servers to be configured for a WAN network.
> Add `wan_dns1` and `wan_dns2`

- go.mod
- go.sum
This contains a fix for unmarshalling of channel fields in JSON, which can contain both numbers and strings.
> Bump SDK to 1.13.1

- .github/workflows/acctest.yml
- docs/resources/network.md
- internal/provider/resource_network.go
- internal/provider/resource_network_test.go
Allows setting the DHCPD boot server and filename attributes of Networks
to enable PXE booting.
> DHCPD Boot Server / Filename

- docs/resources/wlan.md
- internal/provider/markdown.go
- internal/provider/resource_wlan.go
- internal/provider/resource_wlan_test.go
This is to enable setting minimum data rates for 2G and 5G devices on a wireless network.
It relates to the following section in the UI:
The validation on the terraform schema is pulled directly from the UI, I tested a value that is not from the UI and the request failed with status 400.
I am open to suggestion on changing the field names, or potentially using a block instead of a single field so that we can support the other arguments in the future.
> Add minimum_data_rate_2g and minimum_data_rate_5g fields to unifi_wlan

- Makefile
- docker-compose.yaml
- scripts/init.d/demo-mode
Puts the Unifi controller for acceptance testing into demo mode, similar to https://demo.ui.com/ (which doesn't seem to be working at the moment). There are a bunch of other demo-related settings I found, which I haven't implemented but will document here.
- `demo.username` and `demo.password` seem to enable auto-login functionality.
- `demo.num_uap`, `demo.num_usw` and `demo.num_ugw` set the number of test devices.
- I couldn't work out what `demo.mode` or `demo.passthrough.secret` does.
The test devices seem to have incrementing MAC addresses. Switches start at `
00:27:22:00:00:01`, gateways start at `
dc:9f:db:00:00:01` and access points start at `
00:15:6d:00:00:01`.
I want to figure out a way to either automatically adopt all of the test devices or create some sort of adoption …
> Put controller into demo mode

- docs/data-sources/user.md
- docs/resources/user.md
- internal/provider/data_user.go
- internal/provider/resource_user.go
- internal/provider/resource_user_test.go
Supports creating `local_dns_record` entries, added in https://community.ui.com/releases/UniFi-Network-Application-7-2-91/cdac73f0-7426-4276-ace8-8a96c656ba65
> Add support for local_dns_record

- internal/provider/resource_wlan.go
The default was left empty for v5 compatibility, but now that that's been dropped it should default to "both" as per https://github.com/paultyng/terraform-provider-unifi/pull/106#pullrequestreview-605341859.
> Set default wlan band to 'both'

- internal/provider/lazy_client.go
- internal/provider/provider.go
- internal/provider/resource_device.go
- internal/provider/resource_device_test.go
Allow for devices to be adopted on creation and forgotten on destruction. As these could be destructive operations I have made them both opt-in with `allow_adopt` and `forget_on_destroy`.
One issue that I haven't fixed is that the acceptance tests fail with `TEST_COUNT=2` (or any number larger than one). The reason for this is that after forgetting a device it seems to disappear completely for about 30 seconds before it reappears. I wanted to think about this problem a bit more and will submit a follow-up PR to fix it.
> Allow device adoption

- docs/data-sources/network.md
- docs/resources/network.md
- internal/provider/data_network.go
- internal/provider/resource_network.go
- internal/provider/resource_network_test.go
Hi!
First of all, I want to thank you for creating this awesome provider... In combination with Terraform cloud, my home network has gone to the next level :rocket:. Many thanks :)
On Controller `v7`, mDNS was removed (#241) as a global setting and added into each of the networks independently.
This PR adds the setting with a note that it's only supported on controllers `>=v7`.
Note: At first I added unit tests, but it started to get complex because this setting is not supported in all controller versions, also testing every single setting would make the tests hard to read and maintain, so I didn't add a test just for this small setting. If you think it's worth it, I can add the unit test.
> Add support for mDNS on network resource

- internal/provider/resource_port_forward.go
Port forwards are created with `enabled = false` currently, with no way to actually enable them via terraform since `enabled` is deprecated 
Fixes https://github.com/paultyng/terraform-provider-unifi/issues/255
> unifi_port_forward enabled should default to true

- docker-compose.yaml
- scripts/init.d/demo-mode
We currently only need switches for the acceptance tests, so don't provision any access points or gateways.
> Limit number of demo devices

- docker-compose.yaml
Attempting to fix deadlock:
```
[2023-03-01T01:38:21,255] <device-state-check> WARN  monitor - Skipping check for 00:15:6d:00:00:0d, could not acquire lock
com.ubnt.service.lock.D: Failed to acquire lock before timeout
at com.ubnt.service.lock.B.Ô00000(Unknown Source) ~[ace.jar:?]
at com.ubnt.service.lock.ooOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO.Ò00000(Unknown Source) ~[ace.jar:?]
at com.ubnt.service.lock.OooO.while(Unknown Source) ~[ace.jar:?]
at com.ubnt.service.lock.OooO.OO0000(Unknown Source) ~[ace.jar:?]
at com.ubnt.service.lock.OooO.õO0000(Unknown Source) ~[ace.jar:?]
at …
```
> Performance tuning for acceptance tests

- go.mod
- go.sum
Reverts paultyng/terraform-provider-unifi#324. This seems to be causing consistency issues, see https://github.com/paultyng/terraform-provider-unifi/actions/runs/4300078164/jobs/7495937646.
> Revert "Bump github.com/hashicorp/terraform-plugin-docs from 0.13.0 to 0.14.0"

- docs/resources/firewall_rule.md
- internal/provider/resource_firewall_rule.go
- internal/provider/resource_firewall_rule_test.go
Resolves #62
Still need to do doc updates and maybe tests?  First time writing go, so feedback appreciated!
> firewall_rule: Add enabled attribute

- internal/provider/resource_device_test.go
The USW-Leaf consistently fails to be adopted:
```
[2023-03-03T04:25:11,002] XXX <fake-UDC48X6> ERROR inform - dev[00:27:22:00:00:12] failed to update capability: api.err.InvalidReportPort
[2023-03-03T04:25:21,004] XXX <fake-UDC48X6> ERROR inform - dev[00:27:22:00:00:12] failed to update capability: api.err.InvalidReportPort
[2023-03-03T04:25:31,005] XXX <fake-UDC48X6> ERROR inform - dev[00:27:22:00:00:12] failed to update capability: api.err.InvalidReportPort
[2023-03-03T04:25:41,006] XXX <fake-UDC48X6> ERROR inform - dev[00:27:22:00:00:12] failed to update capability: api.err.InvalidReportPort
```
> Don't use USW-Leaf in acceptance tests

- docs/resources/device.md
- examples/resources/unifi_device/resource.tf
- internal/provider/resource_device.go
- internal/provider/resource_device_test.go
> Add support for port aggregation

- .golangci.yaml
See https://github.com/paultyng/terraform-provider-unifi/actions/runs/4368914426/jobs/7642099956.
> Increase `golangci-lint` timeout to 5m

- scripts/init.d/demo-mode
We don't strictly need a gateway, but it makes it easier to poke around the UI.
> Provision a gateway device for acceptance tests

- internal/provider/resource_device.go
- internal/provider/resource_device_test.go
Tested with a `unifi_device` resource controlling a real switch that is powering an old UAP-AC-Lite.
> Support per-port PoE mode override for devices.

- .github/workflows/acctest.yml
According to the thread at https://github.com/hashicorp/terraform-plugin-testing/issues/429 the "text file busy" failure which is currently plaguing the tests is a result of each test case trying to install its temporary copy of Terraform. Pre-installing TF should fix it.
> pre-install TF for acceptance tests
