paultyng/terraform-provider-unifi

- controller.sh
I needed more flexibility for the controller, since all these default ports are already used by my production controller...
> Finetune the controller, make it easier to use

- controller.sh
Based off #9 , just rebased and tested and added minor change.
> Controller reset

- internal/provider/mac.go
- internal/provider/resource_user.go
- internal/provider/resource_user_test.go
Added ip and mac validation for the resource_user
> Add some validations for resource_user

- .gitignore
- Makefile
after merging #9 this one can be merged, making it easy and fast to run the build and test locally with clean environment every time
> Make test options and cleanup afterwards

- internal/provider/resource_network.go
- internal/provider/resource_network_test.go
- internal/provider/strings.go
I wanted to move to using another DNS server at home, so started to codify it in Terraform.
This is my first time contributing to a Terraform provider before, can you let me know what you'd like in terms of testing?
> Initial commit of supporting dns

- docs/resources/port_forward.md
- internal/provider/cidr.go
- internal/provider/cidr_test.go
- internal/provider/resource_network.go
- internal/provider/resource_port_forward.go
- internal/provider/resource_port_forward_test.go
> Add support for CIDR in port forwarding source

- docs/resources/network.md
- examples/resources/unifi_network/resource.tf
- internal/provider/resource_network.go
- internal/provider/resource_network_test.go
Supersedes #70 (squash, rebase and some cleanup)
> Added basic WAN support

- docs/resources/network.md
- docs/resources/wlan.md
- examples/resources/unifi_network/import.sh
- examples/resources/unifi_wlan/import.sh
- internal/provider/importer.go
- internal/provider/provider_test.go
- internal/provider/resource_firewall_group.go
- internal/provider/resource_firewall_rule.go
- internal/provider/resource_network.go
- internal/provider/resource_network_test.go
- internal/provider/resource_port_forward.go
- internal/provider/resource_user.go
- internal/provider/resource_user_group.go
- internal/provider/resource_wlan.go
> Support importing networks and wlans from other sites

- go.mod
- go.sum
> Bump go-unifi to fix #84

- docs/resources/site.md
- docs/resources/user_group.md
- examples/resources/unifi_site/import.sh
- examples/resources/unifi_user_group/import.sh
Add note about how to import a site resource.
> Add site import to docs

- docs/resources/wlan.md
- internal/provider/resource_wlan.go
- internal/provider/resource_wlan_test.go
I see that the tests are failing for the v5 controller. I think I will need some help to resolve them.
> Add wlan_band field to wlan resource

- docs/resources/network.md
- internal/provider/resource_network.go
- internal/provider/resource_network_test.go
> Implement static WAN configuration in unifi_network

- docs/resources/setting_mgmt.md
- internal/provider/resource_setting_mgmt.go
- internal/provider/resource_setting_mgmt_test.go
This depends on: https://github.com/paultyng/go-unifi/pull/41
> Add ssh keys to unifi_setting_mgmt

- docs/resources/wlan.md
- examples/resources/unifi_wlan/resource.tf
- internal/provider/provider.go
- internal/provider/provider_test.go
- internal/provider/resource_wlan.go
- internal/provider/resource_wlan_test.go
> Add WPA3 support to unifi_wlan

- docs/resources/network.md
- internal/provider/resource_network.go
- internal/provider/resource_network_test.go
Fixes #148
~This is probably only supported on v6, so may have to tune the testing.~
> Add support for DHCP relay

- docs/resources/wlan.md
- examples/resources/unifi_wlan/resource.tf
- internal/provider/resource_wlan.go
- internal/provider/resource_wlan_test.go
> Add PMF mode support to unifi_wlan

- scripts/init.d/demo-mode
This should allow us to execute more concurrent acceptance tests in parallel.
> Increase the number of demo devices

- go.mod
- go.sum
- internal/provider/resource_network_test.go
> Add test step removing qos

- Makefile
- internal/provider/resource_wlan_test.go
This doesn't seem to be needed anymore.
> Remove `UNIFI_ACC_WLAN_CONCURRENCY`

- go.mod
- go.sum
- internal/provider/data_account_test.go
- internal/provider/data_ap_group_test.go
- internal/provider/data_network_test.go
- internal/provider/data_port_profile_test.go
- internal/provider/data_user_group_test.go
- internal/provider/data_user_test.go
- internal/provider/provider_test.go
- internal/provider/resource_account_test.go
- internal/provider/resource_device.go
- internal/provider/resource_device_test.go
- internal/provider/resource_dynamic_dns_test.go
- internal/provider/resource_firewall_group_test.go
- internal/provider/resource_firewall_rule_test.go
- internal/provider/resource_network_test.go
- internal/provider/resource_port_forward_test.go
- internal/provider/resource_port_profile_test.go
- internal/provider/resource_radius_profile_test.go
- internal/provider/resource_setting_mgmt_test.go
- internal/provider/resource_setting_radius_test.go
- internal/provider/resource_setting_usg_test.go
- internal/provider/resource_site_test.go
- internal/provider/resource_static_route_test.go
- internal/provider/resource_user_group_test.go
- internal/provider/resource_user_test.go
- internal/provider/resource_wlan_test.go
See https://developer.hashicorp.com/terraform/plugin/testing/migrating.
> Migrate to `terraform-plugin-testing`

- docker-compose.yaml
This reverts commit 38dd4b881f44658d0adfa69d2934e77f86a35cc3. This doesn't seem to be needed.
> Revert "Enable `$LOTSOFDEVICES` (#325)"

- .github/workflows/ci.yaml
- .golangci.yaml
See golangci/golangci-lint-action#677.
> Add `skip-pkg-cache` go `golangci-lint-action`
